### ISSUE TITLE
Panic nil pointer 

### ISSUE THREAD

**Issue by panzerdev** [libdns/autodns#2]
Hi there, I get this nil pointer an wondered if this if statement is maybe wrong an you would just need to create a defaul `http.Client` here?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1045c19ac]

goroutine 1 [running]:
net/http.(*Client).do(0x0, 0x1400015a140)
	/usr/local/go/src/net/http/client.go:606 +0x17c
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:590
github.com/libdns/autodns.(*Provider).makeRequest(0x1400016be90?, 0x10471dd90?)
	/Users/mpanzer/go/pkg/mod/github.com/libdns/autodns@v0.0.0-20241118163948-55a66a54abc3/request.go:68 +0x24
github.com/libdns/autodns.(*Provider).checkZone(0x1400016be90, {0x10471dd90, 0x1048f3e00}, {0x104623b28, 0x20})
	/Users/mpanzer/go/pkg/mod/github.com/libdns/autodns@v0.0.0-20241118163948-55a66a54abc3/sdk.go:27 +0x2a4
github.com/libdns/autodns.(*Provider).GetRecords(0x1400016be90, {0x10471dd90, 0x1048f3e00}, {0x104623b28, 0x20})
	/Users/mpanzer/go/pkg/mod/github.com/libdns/autodns@v0.0.0-20241118163948-55a66a54abc3/provider.go:42 +0x38
main.main()
	/tmp/main.go:16 +0x70
exit status 2
```

https://github.com/libdns/autodns/blob/55a66a54abc31b477438d833b40112998fd5c79f/request.go#L62-L64

**Comment by till** [comment]
Shouldn't be necessary, maybe I forgot to push the branch.

**Comment by till** [comment]
Oh, I see it now. Apologies, you are correct 🫣😩

**Comment by till** [comment]
@panzerdev want to have a look at the PR #3
